"""Business Memory — organizational intelligence that compounds.

The moat: every correction a manager teaches, every recovery the engine
earns, every approval lesson becomes a durable, org-scoped lesson that
future runs RECALL into planning. Lessons are deduplicated and REINFORCED
(noisy-OR confidence, capped) rather than duplicated, so repetition makes
the organization more certain, never noisier.

Scopes propagate learning across the workforce: an `app:SAP` lesson
learned while doing Finance work reaches every future run that touches
SAP — Procurement benefits immediately. Nothing here is generated by an
LLM: rows are written only from human teaching and from measured run
facts (recoveries on the canonical event stream), and recalled verbatim.
"""
from __future__ import annotations

import hashlib
import re
from datetime import datetime, timezone
from typing import Any, Optional

_MAX_EVIDENCE_REFS = 10
_CONFIDENCE_CAP = 0.99
_REINFORCE_GAIN = 0.3   # noisy-OR step per reinforcement

# Words too generic to key a recall on.
_STOPWORDS = {
    "the", "a", "an", "and", "or", "to", "in", "on", "of", "for", "with",
    "open", "click", "type", "into", "then", "verify", "please", "report",
}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _dedup_hash(scope: str, lesson: str) -> str:
    normalized = re.sub(r"\s+", " ", lesson.strip().lower())
    return hashlib.sha256(f"{scope}|{normalized}".encode()).hexdigest()


def record(db, org_id: str, *, kind: str, subject: str, lesson: str,
           source: str, scope: str = "org", workspace_id: Optional[str] = None,
           taught_by: Optional[str] = None, evidence_ref: Optional[dict] = None,
           confidence: float = 0.7) -> dict:
    """Record a lesson, or reinforce it if the organization already knows it."""
    lesson = lesson.strip()
    if not lesson:
        raise ValueError("a lesson needs content")
    h = _dedup_hash(scope, lesson)
    existing = db.table("business_memory").select("*").eq(
        "org_id", org_id).eq("dedup_hash", h).execute().data or []
    if existing:
        row = existing[0]
        refs = list(row.get("evidence") or [])
        if evidence_ref and evidence_ref not in refs:
            refs = (refs + [evidence_ref])[-_MAX_EVIDENCE_REFS:]
        new_conf = min(_CONFIDENCE_CAP,
                       1.0 - (1.0 - float(row.get("confidence") or 0.7)) * (1.0 - _REINFORCE_GAIN))
        patch = {
            "times_reinforced": int(row.get("times_reinforced") or 1) + 1,
            "confidence": round(new_conf, 3),
            "evidence": refs,
            "last_reinforced_at": _now(),
            "archived": False,
        }
        db.table("business_memory").update(patch).eq("id", row["id"]).execute()
        return {**row, **patch}
    row = {
        "org_id": org_id,
        "workspace_id": workspace_id,
        "kind": kind,
        "scope": scope,
        "subject": subject.strip()[:120] or "general",
        "lesson": lesson[:600],
        "source": source,
        "taught_by": taught_by,
        "evidence": [evidence_ref] if evidence_ref else [],
        "confidence": round(min(confidence, _CONFIDENCE_CAP), 3),
        "times_reinforced": 1,
        "dedup_hash": h,
        "last_reinforced_at": _now(),
        "created_at": _now(),
        "archived": False,
    }
    inserted = db.table("business_memory").insert(row).execute().data
    return inserted[0] if inserted else row


def teach(db, org_id: str, user_id: str, *, subject: str, lesson: str,
          kind: str = "correction", scope: str = "org",
          workspace_id: Optional[str] = None,
          evidence_ref: Optional[dict] = None) -> dict:
    """A human teaching the workforce. Taught lessons start more trusted
    than observed ones — a manager's correction is authoritative."""
    return record(db, org_id, kind=kind, subject=subject, lesson=lesson,
                  source="taught", scope=scope, workspace_id=workspace_id,
                  taught_by=user_id, evidence_ref=evidence_ref, confidence=0.9)


def list_memory(db, org_id: str, kind: Optional[str] = None,
                limit: int = 100) -> list[dict]:
    q = db.table("business_memory").select("*").eq("org_id", org_id).eq("archived", False)
    if kind:
        q = q.eq("kind", kind)
    rows = q.order("last_reinforced_at", desc=True).limit(
        min(max(limit, 1), 200)).execute().data or []
    return rows


def archive(db, org_id: str, memory_id: str) -> None:
    db.table("business_memory").update({"archived": True}).eq(
        "id", memory_id).eq("org_id", org_id).execute()


# ------------------------------------------------------------------ recall

def recall(db, org_id: str, terms: list[str], limit: int = 8) -> list[dict]:
    """Lessons relevant to a run, shaped exactly like the engine's local
    knowledge rows ({entity, attribute, value, source, confidence}) so the
    OrgMemoryStore decorator can merge them into the existing recall path.
    Deterministic term match — no LLM in the recall loop."""
    needles = {t.strip().lower() for t in terms if t and len(t.strip()) >= 3}
    needles -= _STOPWORDS
    if not needles:
        return []
    rows = db.table("business_memory").select("*").eq(
        "org_id", org_id).eq("archived", False).order(
        "confidence", desc=True).limit(200).execute().data or []
    hits: list[tuple[float, dict]] = []
    for row in rows:
        haystack = f"{row.get('subject','')} {row.get('lesson','')} {row.get('scope','')}".lower()
        matched = sum(1 for n in needles if n in haystack)
        if matched == 0 and row.get("scope") != "org":
            continue
        # Org-wide policies apply everywhere at reduced priority.
        score = matched + (0.5 if row.get("scope") == "org" else 0.0)
        if score <= 0:
            continue
        hits.append((score * float(row.get("confidence") or 0.5), row))
    hits.sort(key=lambda t: t[0], reverse=True)
    out = []
    for _score, row in hits[:limit]:
        out.append({
            "entity": row.get("subject", ""),
            "attribute": f"{row.get('source','observed')} {row.get('kind','lesson')}"
                         f" (x{row.get('times_reinforced', 1)})",
            "value": row.get("lesson", ""),
            "source": "business_memory",
            "confidence": row.get("confidence", 0.7),
        })
    return out


# ------------------------------------------------ learn from run evidence

def learn_from_events(db, org_id: str, workspace_id: Optional[str],
                      session_id: str, instruction: str,
                      events: list[dict]) -> int:
    """Derive lessons from a finished run's canonical event stream —
    measured facts only. Today: successful recoveries become reusable
    knowledge ("this failure mode occurs here, and this fixed it").
    Returns the number of lessons recorded/reinforced."""
    learned = 0
    focused = ""
    for e in events or []:
        etype = str(e.get("type", ""))
        payload = e.get("payload") or e.get("data") or e
        if etype == "world_snapshot":
            focused = str(payload.get("focused_window") or focused)
            continue
        if etype != "recovery_completed" or not payload.get("recovered"):
            continue
        failure = str(payload.get("failure_type") or payload.get("kind") or "a failure")
        diagnosis = str(payload.get("diagnosis") or payload.get("hypothesis") or "").strip()
        if not diagnosis:
            continue
        app = _app_token(focused) or _app_token(instruction)
        subject = app or "general"
        scope = f"app:{app.lower()}" if app else "org"
        lesson = (f"In {subject}, {failure.replace('_', ' ')} can block progress; "
                  f"recovery that worked: {diagnosis}")
        try:
            record(db, org_id, kind="recovery", subject=subject, lesson=lesson,
                   source="observed", scope=scope, workspace_id=workspace_id,
                   evidence_ref={"session_id": session_id}, confidence=0.6)
            learned += 1
        except Exception:
            continue  # learning is best-effort; it never affects the run
    return learned


def _app_token(text: str) -> str:
    """First meaningful word of a window title / instruction — the app name
    heuristic used only to SCOPE a lesson, never to act."""
    for token in re.split(r"[^\w]+", text or ""):
        t = token.strip()
        if len(t) >= 3 and t.lower() not in _STOPWORDS:
            return t[:40]
    return ""


# ------------------------------------------------ measured insights

def approval_insights(db, org_id: str, threshold: int = 10) -> list[dict]:
    """Autonomous optimization candidates from measured approval history:
    a capability approved N consecutive times with zero denials is a
    standing-approval candidate. Computed live from the approvals table —
    always current, never fabricated."""
    rows = db.table("approvals").select("*").eq("org_id", org_id).order(
        "created_at", desc=True).limit(500).execute().data or []
    streaks: dict[tuple, int] = {}
    closed: set[tuple] = set()
    for row in rows:  # newest first: a streak ends at the first non-approval
        key = (row.get("workspace_id"), row.get("capability"))
        status = row.get("status")
        if status == "pending" or key in closed:
            continue
        if status == "approved":
            streaks[key] = streaks.get(key, 0) + 1
        else:
            closed.add(key)
    out = []
    for (workspace_id, capability), n in streaks.items():
        if n >= threshold:
            out.append({
                "kind": "standing_approval_candidate",
                "capability": capability,
                "workspace_id": workspace_id,
                "consecutive_approvals": n,
                "recommendation": (
                    f"'{capability}' has been approved {n} consecutive times with "
                    f"no denials — consider granting standing approval so this "
                    f"work stops waiting on a human."),
            })
    out.sort(key=lambda i: -i["consecutive_approvals"])
    return out
